### ISSUE TITLE
error: Couldn't create a required mlc01 subfolder or file! (hard time finding out how to reset Cemu from frozen state)

### ISSUE THREAD

**Issue by mlzummo** [emiyl/cemu-macos-compatibility#30]
Getting the following error when trying to start cemu: 

(application is frozen after this and cannot access application settings to possibly reset)

----------
Couldn't create a required mlc01 subfolder or file!

Error: filesystem error: in create_directories: Permission denied ["/Volumes/EXT-500GB"]
Target path:
/Volumes/EXT-500GB/Pre-08-2023/bow/CEMU Breath of the Wild Pack [FINAL] [EUR]/Cemu/mlc01
have tried 
----------

I can no longer have that volume and or drive. Where can I find where it's loading that data from and delete the item-entry

Question: 

how can I reset CEMU so it loads the first time running screen? 
I have tried looking in the Activity Monitor and viewing the open files connected to the process (no luck there either)

I have tried the below as well:

1) deleting the config directories
2) reinstalling the app and other versions

https://cemu.emiyl.com/installation

**Comment by JaimieVandenbergh** [comment]
Try dumping your own game and setting Cemu up as per the guide, instead of using a badly made pirate pack. https://cemu.cfw.guide/installing-cemu.html

**Comment by mlzummo** [comment]
I no longer have that "volume"; Cemu for Mac, simply has a config file its writing somewhere in MacOS that I cannot find that is outside the .app Content plists, and it keeps wanting to load a location that does not exist.

Any help with finding that file or Cemu cli flag to reset?

**Comment by mlzummo** [comment]
solved by deleting /Users/{user}/Library/Application Support/Cemu
