### ISSUE TITLE
Latest Commit no longer builds

### ISSUE THREAD

**Issue by vesper8** [emiyl/cemu-macos-compatibility#7]
A few days ago you could grab the latest build for the latest commit on https://cemu.emiyl.com/installation

But as of right now that's no longer available and only the latest pre-release is.

A lot of people are trying to get the latest commit build because it adds a lot more performance than the latest pre-release since the release of molten-vk 1.2

Hoping you can fix whatever caused this change :)

Cheers!

**Comment by emiyl** [comment]
I'm aware of this and will hopefully get around to fixing it soon.

MoltenVK 1.2 is not yet bundled with Cemu, so using the latest commit will not affect the MoltenVK version.

**Comment by emiyl** [comment]
Took a quick look at it and I didn't figure out what was wrong. Either way, it's started working again since the latest commit, so I'm happy to leave it be unless it becomes a permanent issue.
